# Generated by Django 4.2 on 2023-05-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_offer_price_alter_pizza_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
