# Generated by Django 4.2 on 2023-05-09 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="order_id",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="product_id",
            new_name="product",
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="house_number",
            field=models.CharField(max_length=255),
        ),
    ]
