# Generated by Django 4.2 on 2023-05-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_secondinfowindow"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SecondInfoWindow",
        ),
    ]
