# Generated by Django 4.2 on 2023-05-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_profile_country"),
        ("checkout", "0002_alter_paymentdetails_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.country",
            ),
            preserve_default=False,
        ),
    ]
