# Generated by Django 4.2 on 2023-05-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_remove_order_contact_id_remove_order_payment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="card_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="cvc_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="expiration_date",
            field=models.DateField(),
        ),
    ]
