# Generated by Django 4.2 on 2023-05-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_paymentdetails_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mammaþin", models.CharField(max_length=100)),
                ("eitthvad", models.CharField(max_length=100)),
                ("koolbro", models.CharField(max_length=100)),
                ("okok", models.CharField(max_length=100)),
            ],
        ),
    ]
