# Generated by Django 4.2 on 2023-05-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='kkkak', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='jdjdj', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='ssds', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='house_number',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=23455),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.IntegerField(default=222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='street_name',
            field=models.CharField(default='kekekmd', max_length=50),
            preserve_default=False,
        ),
    ]
