# Generated by Django 4.2 on 2023-05-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_country_remove_profile_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.country",
            ),
            preserve_default=False,
        ),
    ]
